nurione/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from nurione import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'sccapi.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^$', views.index, name='index'),
    url(r'^$', views.post_list, name='post_list'),
    url(r'post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
]

sccapi/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from apitest import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'sccapi.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^apitest/', include('apitest.urls', namespace="apitest")),
    url(r'^nurione/', include('nurione.urls', namespace="nurione")),
    url(r'^admin/', include(admin.site.urls)),
]

nurione/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals

from django.db import models

class TcEntries(models.Model):
    blogid = models.IntegerField()
    userid = models.IntegerField()
    id = models.IntegerField(primary_key=True)
    draft = models.IntegerField()
    visibility = models.IntegerField()
    starred = models.IntegerField()
    category = models.IntegerField()
    title = models.CharField(max_length=255)
    slogan = models.CharField(max_length=255)
    content = models.TextField()
    contentformatter = models.CharField(db_column='contentFormatter', max_length=32)  # Field name made lowercase.
    contenteditor = models.CharField(db_column='contentEditor', max_length=32)  # Field name made lowercase.
    location = models.CharField(max_length=255)
    password = models.CharField(max_length=32, blank=True, null=True)
    acceptcomment = models.IntegerField(db_column='acceptComment')  # Field name made lowercase.
    accepttrackback = models.IntegerField(db_column='acceptTrackback')  # Field name made lowercase.
    published = models.IntegerField()
    created = models.IntegerField()
    modified = models.IntegerField()
    comments = models.IntegerField()
    trackbacks = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'tc_Entries'
        unique_together = (('blogid', 'id', 'draft', 'category', 'published'),)

class News(models.Model):
    code = models.IntegerField(primary_key=True)
    news_key = models.CharField(max_length=50, blank=True, null=True)
    src = models.CharField(max_length=10)
    kind = models.CharField(max_length=3)
    reg_date = models.DateTimeField(blank=True, null=True)
    upt_date = models.DateTimeField(blank=True, null=True)
    pub_yn = models.CharField(max_length=1)
    title = models.CharField(max_length=200, blank=True, null=True)
    hitcnt = models.IntegerField()
    youtube = models.CharField(max_length=60, blank=True, null=True)
    path = models.CharField(max_length=15, blank=True, null=True)
    thumbnail = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'news'

nurione/forms.py
from django import forms
from .models import TcEntries

class PostForm(forms.ModelForm):
    class Meta:
        model = TcEntries
        fields = ('title', 'content',)

nurione/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import TcEntries
from .forms import PostForm

def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.blogid = 1
			#post.published_date = timezone.now()
			post.save()
			return redirect('nurione:post_detail', pk=post.pk)
	else:
		form = PostForm()
		return render(request, 'nurione/post_edit.html', {'form' : form})

def post_list(request):
	posts = TcEntries.objects.using('nurione').filter(created__startswith='12').order_by('-created')[:5]
	return render(request, 'nurione/post_list.html', {'posts' : posts})

def post_detail(request, pk):
	#post = get_object_or_404(TcEntries, pk=pk)
	post = TcEntries.objects.using('nurione').get(pk=pk)
	return render(request, 'nurione/post_detail.html', {'post' : post})

nurione/templates/nurione/base.html
{% load staticfiles %}
<html>
        <head>
            <title>DB connection test sample</title>
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
            <link rel="stylesheet" href="{% static 'nurione.css' %}">
             <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        </head>
<body>
    <div class="page-header">
        <a href="{% url 'nurione:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <h1><a href="/">Post</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>


    </html>

nurione/templates/nurione/post_detail.html
    <div class="post">
        {% if post.created %}
            <div class="date">
               <h1> {{ post.title }} </h1>
            </div>
        {% endif %}
        <p>{{ post.content|safe }}</p>
    </div>

nurione/templates/nurione/post_edit.html
{% extends 'nurione/base.html' %}

{% block content %}
	<h1>New post</h1>
	<form method="POST" class="post-form">{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">SAVE</button>
	</form>
{% endblock %}

nurione/templates/nurione/post_list.html
{% extends 'nurione/base.html' %}

{% block content %}

   {% for post in posts %}
                <div class="post">
                    <div class="date">
                        {{ post.published|date:"Y m d H i s" }}
                    </div>
                    <h1><a href="{% url 'nurione:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
			{% autoescape off %}
			{{ post.content|truncatechars:20 }}
			{% endautoescape %}
                </div>
   {% endfor %}

{% endblock content %}